
services:

  app_db:
    container_name: app_db
    hostname: app_db
    image: library/postgres:14.1
    env_file:
      - .env
    volumes:
      - app_pg_data:/var/lib/postgresql/data
      - app_pg_data_backups:/backups
      - ./scripts/postgres:/scripts
    ports:
      - "65432:5432"
volumes:
  app_pg_data:
    driver: "local"
  app_pg_data_backups:
    driver: "local"

#networks:
#  default:
#    external: true
#    name: 21yard
